import './globals.css'
import type { Metadata } from 'next'
import { Inter, Calistoga } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const calistoga = Calistoga({
  weight: ['400'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Cartas de soledad',
  description: 'Generated by create next app'
}

function Send () {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" strokeWidth="2" stroke="#fff" fill="none" strokeLinecap="round" strokeLinejoin="round">
       <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
       <path d="M15 10l-4 4l6 6l4 -16l-18 7l4 2l2 6l3 -4"></path>
    </svg>
  )
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={`${inter.className} max-w-[1000px] mx-auto min-h-screen grid place-content-center grid-cols-[65%,1fr] gap-8 bg-[#fffef5]`}>
        <main className='text-[#333] grid gap-4'>
          <h1 className={`${calistoga.className} text-6xl`}>Cuéntame<br />de tu soledad</h1>
          <p className='[text-wrap:balance]'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Animi iste dolorum, sunt optio fugiat similique fugit minus,
            esse molestiae doloribus, aut aspernatur voluptatum voluptatem amet.
            Excepturi sit ipsum autem ullam.
          </p>
          <form className='relative'>
            <textarea
              className='bg-slate-100 text-[#333] w-full h-80 p-4 resize-none rounded-md border border-slate-200 shadow-sm focus:outline focus:outline-offset-0 focus:outline-2 focus:outline-slate-300'
              placeholder='Escribe aquí...'
            >
            </textarea>
            <button className='w-9 grid place-content-center absolute bottom-4 right-5 aspect-square rounded-full border bg-blue-600 hover:scale-105 hover:transition-all'>
              <Send />
            </button>
          </form>
        </main>
        <aside className='flex flex-col justify-start items-center'>
          <img width={'200px'} height={'225px'} src="/florciña.png" alt="estampilla" className='-rotate-[8deg]' />
        </aside>
      </body>
    </html>
  )
}
